SELECT
    A.ANIMAL_ID,
    A.ANIMAL_TYPE,
    A.NAME
FROM
    ANIMAL_OUTS AS A,
    ANIMAL_INS AS B
WHERE
    A.ANIMAL_ID = B.ANIMAL_ID
AND
    A.SEX_UPON_OUTCOME != B.SEX_UPON_INTAKE
ORDER BY
    A.ANIMAL_ID
    