SELECT
    B.INGREDIENT_TYPE,
    SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    (SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM
        FIRST_HALF
     GROUP BY
        FLAVOR
    ) AS A,
    (SELECT
        *
    FROM
        ICECREAM_INFO
    ) AS B
WHERE
    A.FLAVOR = B.FLAVOR
GROUP BY
    B.INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER ASC
    